### ISSUE TITLE
Editing a note is hidden by other widgets

### ISSUE THREAD

**Issue by sergeifilippov** [barrelstrength/craft-sprout-notes#7]
In the Dashboard, when you try to edit the note, the edit form expands but it hidden by any other widget that is under the notes widget.

![sprout-note](https://user-images.githubusercontent.com/123676/37492287-a851b024-2905-11e8-8c95-0c7b2d4d6044.gif)

### Server Stack:

- Craft Pro 3.0.0-RC15
- yii 2.0.14.2
- Sprout Notes 2.0.9
- nginx 1.13.9
- php7.1 - 7.1.14
- percona-mysql.5.7 MySQL 5.7.21

**Comment by BenParizek** [comment]
Thanks @sergeifilippov. I can recreate. We'll look into it.
